module.exports = {
    option: {
        ALPHA_PESOS: '20',
        ALPHA_PESOS_PLUS: '101',
        ALPHA_AHORRO: '39',
        ALPHA_RENTA_CAPITAL_PESOS: '21',
        ALPHA_RENTA_CAPITAL: '105',
        ALPHA_RENTA_COBERTURA: '3',
        ALPHA_RENTA_FIJA_GLOBAL: '113',
        ALPHA_PLANEAMIENTO_CONSERVADOR: '108',
        ALPHA_ACCIONES: '1',
        ALPHA_MEGA: '4',
        ALPHA_MERCOSUR: '104',
        ALPHA_RECURSOS_NATURALES: '106',
        ALPHA_RETORNO_TOTAL: '110',
        ALPHA_PLANEAMIENTO_EQUILIBRADO: '112',
        ALPHA_PLANEAMIENTO_DINAMICO: '111'
    }
}